### ISSUE TITLE
Missing types after update

### ISSUE THREAD

**Issue by PssbleTrngle** [Prunoideae/ProbeJS#6] opened 2022-10-31 15:56 UTC
After the latest update there are some types for specific methods that are no longer generated:

![image](https://user-images.githubusercontent.com/12880806/199051758-0f3bcc3d-ee8d-46f9-8bdf-aa03dc9d26d2.png)

This includes the `remove`, `shapeless` and `shaped` methods of the `RecipeEventJS` class. The only types generated are these:
![image](https://user-images.githubusercontent.com/12880806/199052041-0d9b18cd-35de-4ce4-b5f5-e3390ff4ec1b.png)

**Comment by Prunoideae** [comment] 2022-11-01 01:39
Looks like the problem is with Rhino's remapper, this will be fixed after some newer versions of Rhino is pushed out, especially for https://github.com/KubeJS-Mods/Rhino/commit/9949561c3c3c7878a2b98980ab47c79624e3c908 to be merged into 1.18.

**Closed as completed** 2022-11-08 14:41 UTC
Labels: bug
